### ISSUE TITLE
[Sailfish] add "export/save to calendar"

### ISSUE THREAD

**Issue by cnlpete** [smurfy/fahrplan#109]

**Comment by smurfy** [comment]
I started messing around with sailfish calendar support, but currently failing because fahrplan does not run as priveleged user. (needed to access the calendar)

**Comment by smurfy** [comment]
Ok, Calendar support now works with sailfish, 
I need to add some switch to enable / disable it based on if i compile it for harbor or openrepro but it works. :D

**Comment by smurfy** [comment]
added with PR #168

**Comment by cnlpete** [comment]
awesome, can't wait for the next release. Thanks!
