### ISSUE TITLE
[Ubuntu Touch] Fahrplan use the sdk's native date time picker

### ISSUE THREAD

**Issue by krnekhelesh** [smurfy/fahrplan#137]
The Ubuntu SDK provides a date time picker which is well tested and should be used instead of the custom component which is currently being used.

**Comment by mzanetti** [comment]
this has been fixed and realeased

**Comment by smurfy** [comment]
@mzanetti What exactly do you mean? There are still custom date and time picker components in the ubuntus gui folder.

**Comment by mzanetti** [comment]
Hmm... for some reason I thought Nekhelesh fixed this already... looking at the ui I confused them with the upstream pickers.

I've just tried to update to the SDK ones, but seems there is a bug with the time picker. I can't really initialize it properly. So leaving this as is for mow.

**Comment by smurfy** [comment]
Ok, no problem, as far as i know Nekhelesh  wanted to do it, but i guess he did not have the time yet :).

**Comment by krnekhelesh** [comment]
@smurfy @mzanetti Sry about this, I had a branch earlier which got stalled due to lack of time. But anyway, I started fresh and have fixed this. Will create a pull request tonight. Happy to see a lot of custom code being removed.

**Comment by krnekhelesh** [comment]
This has been fixed as well.
