### ISSUE TITLE
[BB10] Text not fully visible on 720x720 resolution devices

### ISSUE THREAD

**Issue by stmblfrcr** [smurfy/fahrplan#141]
After a long press on Departure, Stoppover or Arrival, the Options to switch Stations are not fully displayed/cut off on my Q5.
![img_20141126_122041](https://cloud.githubusercontent.com/assets/9961488/5200617/e9d0056e-7567-11e4-8304-d76c1dcdd968.png)

**Comment by leppa** [comment]
Hi @stmblfrcr,
Could check the latest update, please, and tell me if it resolves the issue? Version 2.0.25 was approved in BlackBerry World today.

**Comment by stmblfrcr** [comment]
Sorry, just read your post. Yeah - it's certainly resolved now! It actually took some getting used to NOT having the giant UI elements anymore :-). https://github.com/smurfy/fahrplan/issues/146 is fixed now as well. 
![Uploading IMG_20150329_131218.png . . .]()
![Uploading IMG_20150329_131528.png . . .]()
![Uploading IMG_20150329_131437.png . . .]()
![Uploading IMG_20150329_131346.png . . .]()

Thank you!

**Comment by leppa** [comment]
Great to hear that. Still seems to be cut a little bit on the sides, but much better now.

Regarding the smaller elements: are they big enough to be readable? Unfortunately, DPI related issues are not something you can easily test on the simulator.

**Comment by stmblfrcr** [comment]
I dusted off my N9 for comparison and the font seems slightly smaller on BlackBerry (minus 0.5/1) but better readable and sharper so that's alright I guess. Although the blue flip switches still seem to be improperly big (at least a little).

**Comment by leppa** [comment]
Thanks a lot for your tests!
Symbian components were never meant for HiDPI screens, so I assume that there are still some visibility issues until #100 is done.

**Comment by stmblfrcr** [comment]
Sure thing! I saw you put TAO Translator in Beta Zone (great btw) as a Cascades app.
