### ISSUE TITLE
[BB10]: Text not fully visible

### ISSUE THREAD

**Issue by gemueselasagne** [smurfy/fahrplan#146]
Hi!
Thanks for your effort! Best transport App on BB10 right now!

On Q10 the text in the background in the find-station dialogue doesn't look as it's supposed to. Fixing that would give the app a more professional look!

Thanks

![img_20141213_174730](https://cloud.githubusercontent.com/assets/10177993/5424480/f9575bfe-82f0-11e4-94c0-d60dd5146e9c.png)

**Comment by leppa** [comment]
Closing as @stmblfrcr reported it as fixed in #141.
