### ISSUE TITLE
[BB10]: Time format is confusing

### ISSUE THREAD

**Issue by gemueselasagne** [smurfy/fahrplan#147]
Hey!
Thanks for your work on fahrplan!

For me, the time format is a bit confusing. It's starts with the fact that 12-hours format is used instead of 24-hours format. In most parts of europe 24-hours format is common. The app would be easier to use if you'd switch time formatting to 24-hours standard.
There is also a tiny problem with the german translation. In the results-view it says 'AM' and 'PM'. In detail-view it says 'NACHM.' and 'VORMM.' which is not common at all and takes away a lot of space.

Thanks for your work!

![img_20141213_175725](https://cloud.githubusercontent.com/assets/10177993/5424509/28e11198-82f2-11e4-8e42-029198733c45.png)
![img_20141213_175721](https://cloud.githubusercontent.com/assets/10177993/5424510/2ae5202e-82f2-11e4-8ea2-7c3095c629d1.png)

**Comment by ServMan** [comment]
This issue has been solved with the release of BlackBerry OS version 10.3.1 on Feb 19, 2015!
Time display is now back to 24 h automatically!

**Comment by leppa** [comment]
Happy to hear that. It looks like this was indeed an OS bug. I'm closing the bug, but I think we should still think about bringing 12/24H option to settings.
