### ISSUE TITLE
Icon should be updated

### ISSUE THREAD

**Issue by kayschubertwebde** [smurfy/fahrplan#156]
the icon is a little outdated, on Symbian it is to big and the rail is not in the middle, on AppList exists a reworked icon, you should ask Sebastian for providing it

**Comment by leppa** [comment]
I'll take care about that as soon as my time permits. I also noticed misalignment of the rail and absence of the gradient on Sybmian, so I started fixing the issue around New Year time. The icon on AppList is actually the one I sent to Sebastian and it's done based on Nokia's templates and guidelines. It's just not completely ready for submission yet and I didn't have time to finish it.
