### ISSUE TITLE
Backend names should be more descriptive

### ISSUE THREAD

**Issue by mzanetti** [smurfy/fahrplan#160]
The backend selection list is not entirely great imo. The issues are:

* Mix between urls and descriptive names (bahn.de vs SF Bay Area)

* It's not entirely clear which area is supported by a backend. For example I'm in Brussels right now and someone else had to tell me I could use the app with the 9292ov.nl backend around here.

IMO there should be some naming convention like "Area (service)" or similar:

Germany (bahn.de)
Netherlands/Belgium (9292ov.nl)
...

**Comment by smurfy** [comment]
I'm with you on that one.

**Comment by smurfy** [comment]
Updated all names and normalized the way they are set.
Also added German translation. 
Needs some testing in frontends displaying the current selection on the main screen.

**Comment by mzanetti** [comment]
Tested on Ubuntu, looks ok. The selection list doesn't always fit the full provider url, however, once selected all of them fit into the main view where it shows the currently used backed. All the Country names are visible in the selection list too, which I consider the important part.
