### ISSUE TITLE
[Request] Button to interchange destination and departure station

### ISSUE THREAD

**Issue by tooka** [smurfy/fahrplan#161]
Hey, I'm using the fahrplan app (N9 in my case), most of the time to get to work and back. It would be a great help to have a little button at the side or bottom to interchange the destination and departure station quikly, without the need to choose/search them again.
Is it possible with not so much effort?
Greetings
Tom

**Comment by leppa** [comment]
Long tap on the station and context menu will pop-up. There you can clear current station or swap with another one.

**Comment by tooka** [comment]
Whaaa, oh man. Thanks leppa. Case closed. Reason: dumb user ;-)

**Comment by leppa** [comment]
Well, I wouldn't say dumb. It just seems to be not intuitive enough: long tap to get context menu paradigm seems to become less and less common nowadays.

**Comment by stmblfrcr** [comment]
For me a long tap only gives options to choose or switch stations. Was it possible before to clear a station? This started to gather some negative reviews on BB World as well and should be included in the description maybe. Regards.

**Comment by leppa** [comment]
@stmblfrcr, do you have device with hardware keyboard? Departure, Via, Arrival and Direction stations all have "Clear station" in context menu. If you have only three items there, did you try scrolling the menu? Unfortunately, I don't have a real device with hardware keyboard / square screen and, as far as I remember, on simulator all four menu items were displayed without the need to scroll.

**Comment by stmblfrcr** [comment]
Oops...so you can actually scroll and it's just that the bar is not visible. I am on a device with hardware keyboard and it looks like this - https://github.com/smurfy/fahrplan/issues/141 . Thank your very much, works for me.

**Comment by leppa** [comment]
So context menu is cut on the sides for you too? I didn't have time to look into that bug yet, unfortunately.

**Comment by stmblfrcr** [comment]
Yeah. It's a rather small bug and I'm totally fine with it for the time being. I guess it's pretty understandable with the exotic square aspect ratio.
