### ISSUE TITLE
Deutschland München MVV Backend only missing line only in travel overview 

### ISSUE THREAD

**Issue by DeadHorseRiding** [smurfy/fahrplan#163]
Tested on N9
![20150306213228](https://cloud.githubusercontent.com/assets/10514536/6543411/cf793e62-c51a-11e4-8566-1538c45c551d.png)
![20150306213302](https://cloud.githubusercontent.com/assets/10514536/6543410/cf7898fe-c51a-11e4-96b0-88086fe952d3.png)

Kalendereintrag korrekt, Reiseübersicht gekürzt (vgl Bilder)

Am Rande: Transifex String 322 Gleis %1 findet hier keine Verwendung, so daß die 1 (Gleis?) allein steht?

Besten Dank...

Calendar correct - travel overview shortened.
Transifex String 322 Track %1 not used for MVV Backend?

Thank you very much.

**Comment by smurfy** [comment]
thanks, will check

**Comment by smurfy** [comment]
Ok, i can reproduce the error, will have a look at the actual code to reproduce it.

**Comment by DeadHorseRiding** [comment]
Thanks.

**Comment by smurfy** [comment]
Possible fix commited as PR.
