### ISSUE TITLE
v 2.0.24 temporärer Fehler 9380 mit Bahn.de Backend 

### ISSUE THREAD

**Issue by DeadHorseRiding** [smurfy/fahrplan#179]
Hallo,
sicher nur Backend Fehler, MVV München lieferte zur selben Zeit Ergebnisse, nicht mal eine Stunde später ging auch Bahn.de wieder.
![2015-03-23_08-36-41](https://cloud.githubusercontent.com/assets/10514536/6779588/e65692ca-d15d-11e4-9184-028446d63ddd.png)

DAnke auch fürs neue Update auf 2.0.25!

Gruß aus München

**Comment by smurfy** [comment]
i need to check what the 9380 code means

**Comment by leppa** [comment]
It seems to mean *Dep./Arr./Intermed. or equivalent station defined more than once*.

**Comment by smurfy** [comment]
Ok, you can see "something" via "Unterföhring" to "Unterföhring" which is exactly what your error message is.

**Comment by leppa** [comment]
Nice catch. Then we should add this error description to `ParserHafasBinary::errorString()`.
