### ISSUE TITLE
Save Station

### ISSUE THREAD

**Issue by TuxNix** [smurfy/fahrplan#183]
It would be nice, if this app could save some stations often used.

**Comment by TuxNix** [comment]
I

**Comment by TuxNix** [comment]
It would be nice, if this app could save some statons often used.

**Comment by leppa** [comment]
Thank you for your suggestion. Sounds like a duplicate of #144. Is that something you suggest?

**Comment by TuxNix** [comment]
Yes Leppa, it is the same idea.

**Comment by smurfy** [comment]
Ok, so i close this, as duplicate :) 
But yea, such a feature would be great.
