### ISSUE TITLE
Correcting station name in search field results in no stations found

### ISSUE THREAD

**Issue by abkro** [smurfy/fahrplan#188]
I have used Fahrplan for a few days with the Norwegian API reiseinfo.no/nri. If I type a station name in the search field a list of suggestions appears. If I abandon the search term, either by deleting it character by character, or by tapping on the 'x' in the search field, it is no longer possible to search for stations. No matter what I type, (including the original term) no suggestions appear. I have to hit the 'back' icon at the top and reenter the search field in order for it to work again.

Kind regards,
Ari

**Comment by mzanetti** [comment]
Is this on Ubuntu? If so, this bug is fixed in git master with commit f39dc10, but not released into the App Store yet.

**Comment by abkro** [comment]
Yes it's on Ubuntu. Thanks. Look forward to updating to the new version! 

(I also wrote a short review in the App store where I mentioned problems with the nordic characters åæø. Should I register a bug report here for this issue?)

**Comment by mzanetti** [comment]
Yes. Please report bugs. The reviews in the store are not the right place for reporting bugs for multiple reasons.

**Comment by smurfy** [comment]
I will close this issue. @abkro please report the characters or any other problem as a separate issue.
Thank you.
