### ISSUE TITLE
9292ov.nl data source is missing delays, train cancellation warning messages

### ISSUE THREAD

**Issue by krnekhelesh** [smurfy/fahrplan#202]
I have noticed during daily usage that fahrplan doesn't show train delays, cancellation warning messages that the official 9292ov.nl app on android shows. Here is a screenshot of a warning that is shown in the timetable page on android that isn't shown with fahrplan.

![screenshot_2015-05-21-15-38-04](https://cloud.githubusercontent.com/assets/761845/7749994/dde5cf5a-ffd1-11e4-9f30-34a8f99c2ec7.png)

**Comment by leppa** [comment]
Moreover, it doesn't show line numbers (e.g., just "Intercity", instead of "Intercity 241", for Amsterdam -> Berlin route). It definitely needs some love.

PS: I've fixed line numbers display when I was in Amsterdam last time. Just didn't have time to clean up and submit the code.

**Comment by krnekhelesh** [comment]
@leppa ooh yes showing "Bus 69" to Delft Central rather than just "Bus" would be much appreciated.

**Comment by krnekhelesh** [comment]
@leppa It looks like this issue can now be closed as I can see delays and other warnings thanks to your pull request #206.

**Comment by leppa** [comment]
It's still missing delays in journey details, like official app has, but I don't see this data in JSON reply. So it can be closed.
