### ISSUE TITLE
Developer Information in About Screen

### ISSUE THREAD

**Issue by kayschubertwebde** [smurfy/fahrplan#211]
1. Two main developers are still listed under co-developers.
2. Co-developers should be sorted in alphabetical order.

**Comment by smurfy** [comment]
All Developers are listed in the "code contibutors" list. (except me)
Other thing is "maintainers" not main developers. It specifies who is keeping fahrplan up to date and makes sure the platform is still supported.

@mzanetti looks mainly after ubuntu phone
@leppa has a bb10 phone and maintains the port, also did the symbian port and has vaste knowlege of qt.
@smurfy (me) is the original author, mainly working on the backends, and harmattan/sailfish gui.

**Comment by kayschubertwebde** [comment]
I was referring to the german translations "Hauptentwickler" and "Mitentwickler". So it seems redundant to me to list some developers under both. Maybe for better understanding the terms should be changed to "Plattform-Betreuer" and "Entwickler" and also mention the platform each maintains.

The wrong sorting of the developers still applies.

**Comment by smurfy** [comment]
Ok, i will have a look
