### ISSUE TITLE
[Ubuntu Touch] German translation incomplete (main screens)

### ISSUE THREAD

**Issue by bittner** [smurfy/fahrplan#217]
On Ubuntu Touch Fahrplan v2.0.25 shows English labels on the two main screens, all the other translations seem to work fine.

Tested with providers "Schweiz (sbb.ch)", "Österreich (oebb.at)", "Deutschland (bahn.de)".

## Missing (or not displayed) translations

1. **Screen "Fahrt"**
   * "From" -> "Von"
   * "Via" -> "Über"
   * "To" -> "Nach"
   * "Date and time" -> "Datum und Zeit"
   * "Transport Options" -> "Verkehrsmittel" (?)
   * --> popup screen "Select transport mode" -> "Verkehrsmittel auswählen" (?)
1. **Screen "Zeitplan"**
   * "Date and time" -> (same as above)
   * "Transport Options" -> (same as above)

**Comment by smurfy** [comment]
Translations are managed via transifex (https://www.transifex.com/leppa/fahrplan/)

**Comment by leppa** [comment]
German strings in Transifex are at 100%. Either we're missing some in the translation source, or Transifex is outdated. I can check.

**Comment by leppa** [comment]
The translation source was outdated. Now we have some untranslated strings there.

**Comment by bittner** [comment]
German translation is now complete, though review is pending for some items.

* 11 items still waiting for [review](https://www.transifex.com/leppa/fahrplan/translate/#de/en/41276321?reviewed=no) (Sailfish or translations you should look at for another reason).
* 3 items are marked as [issues](https://www.transifex.com/leppa/fahrplan/translate/#de/en/41276321?issue=yes) (need changes in the source code).

I've reviewed the obvious changes myself, including spelling changes related to "ß" (scharfes S), e.g. "Schließen", "Fußweg". (We're not using Swiss German, are we?)

**Comment by bittner** [comment]
Still 11 items waiting for review and 3 items marked as issues on Transifex. :disappointed: 

Is there anything more I can do to help? Anything I can clarify on that?

**Comment by smurfy** [comment]
Everything is fine, i just had not much time, sorry.

I reviewed everything now, 

Copyright/License on Ubuntu should be changed, i will do that in source soon.
I also normalized the translation of Backend to Datenquelle everywhere. (Old was Anbieter or Backend)
