### ISSUE TITLE
ÖBB requests seem not to work anymore

### ISSUE THREAD

**Issue by jv-barsuk** [smurfy/fahrplan#218]
Since the ÖBB changed there schedule last week the requests seem not to work anymore.

**Comment by jv-barsuk** [comment]
http://oebb.at seems to be purged, only http://www.oebb.at works in the browser.

**Comment by jv-barsuk** [comment]
http://oebb.at seems to be purged, only http://www.oebb.at works in the browser.

**Comment by smurfy** [comment]
Works for me.

What Platform and Version do you use?

**Comment by jv-barsuk** [comment]
Actually there was another issue. I had the same station in the from and in the via field, that seems to be the reason why it didn't work, even though it happened after the update of the train schedule.

I did actually not know how to clear the via field. Would be nice to be able to do it with a swipe from left to right. Should I report a new issue for this?

**Comment by smurfy** [comment]
> I did actually not know how to clear the via field. Would be nice to be able to do it with a swipe from left to right. Should I report a new issue for this?

Not sure on which platform you are, but normally its press and hold on the station at the main screen.

**Comment by jv-barsuk** [comment]
I'm using Ubuntu-Touch.
