### ISSUE TITLE
Deploy version for SailfishOS-i486 (Tablet)

### ISSUE THREAD

**Issue by manuelbusch** [smurfy/fahrplan#220]
Now, after the first jolla tablets were shipped, it would be great to have the fahrplan app in Harbour and OpenRepos also for i486 (jolla tablet). I've tried to deploy 2.0.26 on my tablet and it seems to work really good. In Harbour admin there is now a compatibility checkbox for the tablet.

Best regards

**Comment by smurfy** [comment]
Will do this as soon i get my tablet. (hopefully i'm in wave 2) , ordered at lunchtime on the 19th.
