### ISSUE TITLE
View intermediate stops for Ubuntu Phone

### ISSUE THREAD

**Issue by MueMar** [smurfy/fahrplan#225]
It would be nice the intermediate stops would be shown if i click between the start and the destination station(bahn.de).

Thanks for the great App!

**Comment by leppa** [comment]
Hi and thanks for your suggestion. This feature was requested long time ago but until now we didn't have time to implement it, unfortunately.

I'm closing your issue as duplicate of #13. You can subscribe to that issue to track the status.
