### ISSUE TITLE
Backend error on Symbian

### ISSUE THREAD

**Issue by Imhotep-2700bc** [smurfy/fahrplan#227]
Hello,
with Fahrplan 2.0.16 on Symbian I get "Unknown error occurred with the backend (Error 12)".
When I try to update to 2.0.26 I get an similiar message "network connection broken, installation aborted".
But I have no problems with the internet connection. Wnt the backend off service?

**Comment by smurfy** [comment]
what backend are you using? bahn.de?

**Comment by Imhotep-2700bc** [comment]
Yes, bahn.de.
And well, I get the error messages in German. My translation may slightly differ from the original English message.
But I suppose, bahn.de has nothing to do with the aborted installation of the update?

**Comment by leppa** [comment]
> When I try to update to 2.0.26 I get an similiar message "network connection broken, installation aborted".

"installation aborted" sounds like an error during installation, not while using the app. Is ti so?
I have a feeling that Nokia Smart Installer, that we use to package Fahrplan, doesn't work anymore. We need to package without it now.

**Comment by Imhotep-2700bc** [comment]
@leppa 
Yes. when I touch the "fahrplan2_2.0.26_installer.sis" file the installation starts with "preparation", goes on with "installing" and stops with "aborted". Then there is a hint that I should continue the installation using the "Nokia Smart Installer ADM" which does not work either.

**Comment by smurfy** [comment]
@leppa do you still have your symbian to test an "smart installer" free installation. i thought it was necessary to use it, for the qt dependencies.

@Imhotep-2700bc 2.0.26 works for me so as long as we get the install problem sorted out i think there is no bug with the bahn.de backend itself.

**Comment by kayschubertwebde** [comment]
The server for the Nokia Smart Installer is down. Please install the AppList store and then install the apps you want. AppList is completely without Nokia Smart Installer. Here you can find Fahrplan:
http://applist.schumi1331.de/content/12

**Comment by Imhotep-2700bc** [comment]
Hello,
installation of AppList and update of Fahrplan worked.
And the backend error is solved with the update.

Thanks a lot for your quick support. It exceeds my expectations.

**Comment by kayschubertwebde** [comment]
I think this problem shows, that it would make sense to set a link also to AppList on the Fahrplan website for an alternative installation source for Symbian (my personal opinion is, that AppList should be the recommended installation source). Please use the provided link.
