### ISSUE TITLE
 "vasttrafik.se", Gothenburg Sweden stopped working 26-27th of february.

### ISSUE THREAD

**Issue by mikaelelf** [smurfy/fahrplan#233]
I use Fahrplan (symbian belle) on regular basis (Gothenburg, Sweden) and today it didn't work. I use "vasttrafik.se" and don't get any departures or arrivals at all since today or yesterday. By the way "resrobot.se" doesn't work either. For a control I tried the German "bahn.de" which do work. Would be very greatful if you could fix the problem!

**Comment by smurfy** [comment]
a new version will be released soon, with fixed vasttraffik and resrobot

**Comment by mikaelelf** [comment]
great, thank you very much!
/mikael
----Originalmeddelande----
Från: Philipp Andreas
Sänt: 2016.02.27, 22.55 
Till: smurfy/fahrplan
Kopia:mikaelelf
Ämne: Re: [fahrplan]  "vasttrafik.se", Gothenburg Sweden stopped working 26-27th of february. (#233)


a new version will be released soon, with fixed vasttraffik and resrobot

---

**Comment by mikaelelf** [comment]
I've seen, that among other OS:es, Meego has been updated in March (to 2.0.27). Will the Symbian version be updated too? Applist still holds 2.0.26.  Thank you!

**Comment by leppa** [comment]
Hi @mikaelelf,

Today I finally found time to build and push an updated version of Fahrplan to AppList. So it should be up to date now. Sorry for such a delay.

**Comment by mikaelelf** [comment]
Hi @leppa,  the newly uploaded version 2.0.27 on applist works fine with "resrobot" but not with "vasttrafik". If using "vasttrafik" searches for bus/tram/train stops become eternal and with no result.

**Comment by leppa** [comment]
I submitted the same version as published on all other platforms (except for encoding fix which is not related to vasttrafik.se).

It seems to work on Jolla and BlackBerry 10, so might be something Symbian specifik. I'll try to take a look.

**Comment by leppa** [comment]
I checked and it seems that it's a Symbian specific problem now. It might be that Symbian is becoming too old: when Fahrplan uses HTTPS, the connection closes immediately; when HTTPS is disabled, Fahrplan is able to request the access token, but subsequent request to find station fails. So it looks like there might be no way to make Västtrafik work on Symbian.

**Comment by mikaelelf** [comment]
So, has this something to do with the way "vasttrafik" works? Do you think one should expect that  other providers of public transport data will change their way to deliver data in the same direction as "vasttrafik"? 
Good anyway that "resrobot" works so far as it covers a big part of Sweden. A good enough solution is of course to use google maps public transport wayfinder, which still works with google maps 4.1.1 for Symbian. However Fahrplan is much more convenient to use. 

Thanks for your response and investigation!

**Comment by leppa** [comment]
Well, as this issue seems to be related to SSL, api.vasttrafik.se might be using some modern cipher suite that Symbian doesn't support. And, unfortunately, it looks like the without SSL only token request works. I might try to dig deeper whenever I have time, but don't count on it in the nearest time.
