### ISSUE TITLE
Android (Cyanogenmod) support?

### ISSUE THREAD

**Issue by jax667** [smurfy/fahrplan#236]
Hey guys, 

I didn't want to let go of my Nokia 808 (Symbian Belle), but since Nokia dropped Symbian and some apps are harder to use as the years go by (Browser) or just non-existent like a descent messenger app (XMPP client/Signal), I was forced to get an Android Smartphone. 

I would like to know what your standpoint is regarding that operating system. I would love to see one of my favourite apps on F-Droid, for example. Is there a chance that you will publish an Android version of Fahrplan since it should be compatible with Qt?

Kind Regards,
Jax

**Comment by jax667** [comment]
Nevermind guys, I don't want to cause any more work since I found transportr:
https://fossdroid.com/a/liberario.html

**Comment by smurfy** [comment]
another good one is "Oeffi" on android.
