### ISSUE TITLE
Change long-press menu behavior to listitem swipe gestures

### ISSUE THREAD

**Issue by abkro** [smurfy/fahrplan#239]
Old-title: Unable to remove "via" station in search
Hi

I have used Fahrplan for the past year and have constantly had trouble when specifying a search for a journey because I most often do not need the option to specify a "via" station, yet it is impossible to remove this. I therefore end up trying to find some other station along the route I am looking up, so as to be able to complete the search and obtain the desired result.

I am running Fahrplan v. 2.0.26 on Ubuntu phone.

**Comment by mzanetti** [comment]
Does long-press on the via station field not work for you?

**Comment by abkro** [comment]
Hi 

It does indeed work for me, thank you! 

I had no idea that was how it worked! Maybe some kind of tip, or
possibly better still, the ability to toggle the "via" field on/off,
might be more obvious to the user? Just a suggestion... 

(For me, personally, the issue is naturally solved, since I now
understand what to do.) 

Best regards, 

Ari 

Den 14.04.2016 12:46, skrev mzanetti: 

> Does long-press on the via station field not work for you? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [1]
 

Links:
------
[1] https://github.com/smurfy/fahrplan/issues/239#issuecomment-209875820

**Comment by mzanetti** [comment]
Actually, can we reopen this @smurfy ?

I think this long-press menu should be converted to listitem swipe gestures as it is common in ubuntu touch nowadays.
