### ISSUE TITLE
Ambiguity in search results

### ISSUE THREAD

**Issue by M1dgard** [smurfy/fahrplan#241]
If you want to route from a Kerkstraat you also have to type the municipality.

![screenshot](https://cloud.githubusercontent.com/assets/4283376/15100410/100c56f6-1571-11e6-8fb5-e0c5354baf18.png)

Typing "Kerkstraat Amste" still gives two results (Amsterdam and Amstel both have a Kerkstraat).

Ubuntu Touch, Fahrplan v2.0.26

**Comment by leppa** [comment]
I assume you're using 9292ov.nl service?

We display what the service returns to us. If it just returns a list of stations that are all named "Kerkstraat", than we can't do much about that. I'll check whether there's some additional info attached, to distinguish those. If yes, then we should be able to update the service to display it.

**Comment by M1dgard** [comment]
> I assume you're using 9292ov.nl service?

Indeed.

> We display what the service returns to us. If it just returns a list of
> stations that are all named "Kerkstraat", than we can't do much about that.
> I'll check whether there's some additional info attached, to distinguish
> those. If yes, then we should be able to update the service to display it.

I believe it also returns the city. At least, cities are shown when you do a 
search on their website, so it wouldn't really make sense if it's not included 
in their API response.

**Comment by leppa** [comment]
>I believe it also returns the city.

Seems like it does, on the website. In this case, I assume it's also returned through the API, we just didn't include it into our output. I'll try to take a look tomorrow.
