### ISSUE TITLE
[Symbian^3] Vasttrafik (sweden) works again now, but not resrobot (sweden)!

### ISSUE THREAD

**Issue by mikaelelf** [smurfy/fahrplan#247]
Refers to #233.
"Resrobot"  stopped working a few weeks ago, but to my surprise "vasttrafik", which had stopped working do work again!!  Well, this seems shaky and random... Could you check this up please? Why does "vasttrafik" (Gothenburg local public transports) work again and why does "resrobot" (countrywide public transports) not work anymore. Could something be done to safe the availability of these public transport data providers??

**Comment by f03el** [comment]
@mikaelelf  Resrobot is working for me in Sailfish OS. Unfortunately I don't have the possibility to test in Symbian. Is it still not working for you?

**Comment by mikaelelf** [comment]
No, it's not working! Tell me if you want additional informatin.

**Comment by f03el** [comment]
@mikaelelf Do you see anything interesting when running Fahrplan from the command line? Does anything of the following work?
- Find stations by name
- Search journey
- Time table

**Comment by mikaelelf** [comment]
how do I do that? From cmd in delight app? Which command to use?

**Comment by f03el** [comment]
I have never used Symbian, so I can't help there. Does someone else know?

**Comment by f03el** [comment]
Could it be the same problem as #212?

**Comment by mikaelelf** [comment]
I don't know. It searches for a while an then report "no results were found".

**Comment by mikaelelf** [comment]
Additional info: when using the same ver nr of fahrplan on Harmattan, it behaves in the same way as symbian. However updating this version to latest (2.28, not available for symbian ) resrobot.se works.

**Comment by leppa** [comment]
> latest (2.28, not available for symbian )

My fault. I completely forgot to build and upload 2.0.28 to AppList. Will try to do it this week.

**Comment by f03el** [comment]
Aha, that's probably the explanation then. ResRobot changed their API earlier this year, and support for that was fixed in Fahrplan 2.0.28.

**Comment by leppa** [comment]
I just built and uploaded 2.0.28 to AppList.

@mikaelelf, can you try now?

**Comment by mikaelelf** [comment]
sorry, doesn't change anything :(

**Comment by f03el** [comment]
@mikaelelf This is a bit of a long-shot, but just to be able to rule out #212, could you go to https://api.resrobot.se/v2 in the Symbian web browser? You should get a 404 error, but if you get some kind of certificate error, then that could be the problem with Fahrplan.

**Comment by mikaelelf** [comment]
with opera mini a 404 error, with nokia browser "webbrowser cannot connect to the web site".

**Comment by mikaelelf** [comment]
![screen8](https://cloud.githubusercontent.com/assets/17519744/21790956/ec63f2e6-d6df-11e6-9c8f-477af5df1614.jpg)

**Comment by leppa** [comment]
Opera Mini uses Opera's servers to download and render the page, so it might still work there.

Can you open other websites with Nokia Browser?

If yes, then it might be missing root certificate in Symbian Certificate Store.
Or it could be that ResRobot uses protocols/ciphers which are not supported by Symbian.

**Comment by leppa** [comment]
Can you open this page: https://ssltest11.bbtest.net/ in Nokia Browser?

It uses the same Root CA certificate as ResRobot.

**Comment by mikaelelf** [comment]
![screen10](https://cloud.githubusercontent.com/assets/17519744/21809682/13d823e2-d749-11e6-9d70-afdf7586bb7e.jpg)

Looks like this in Nokia Browser.

**Comment by leppa** [comment]
Looks Ok. Then it might be some Symbian-ResRobot incompatibility.

I can see [here](https://www.ssllabs.com/ssltest/analyze.html?d=api.resrobot.se) that ResRobot uses (SNI)[https://en.wikipedia.org/wiki/Server_Name_Indication], which is not supported by Symbian. But you should have gotten an error that certificate doesn't correspond to the domain name, not just "cannot connect" error.

Does this page open for you too: https://ssltest8.bbtest.net/?

**Comment by mikaelelf** [comment]
Yes, looks about the same as the previous page. Though had to make an approval, a dialogue said: The service ssltest8.bbtest.net has sent a none reliable certficate. Accept anyway?

**Comment by leppa** [comment]
Ok, I undusted my old Symbian phone and checked: it's SNI issue. We're aborting SSL connection because of hostname mismatch. This can be ignored for ResRobot parser by Fahrplan and should fix the issue. I'm making a fix.

**Comment by mikaelelf** [comment]
Great to hear, thanks for you work 😁! Fahrplan is about my most important app. Even the wayfinder (which had a public transport part built in) in googles map app stopped working some months ago.

**Comment by mikaelelf** [comment]
just one question: Will this fix show up in a later  update or will we see a specific symbian update on app list?

**Comment by smurfy** [comment]
I will have a look, we can do a symbian only update but i will have a look if there are other bugs around. I plan to do the release early next week.

**Comment by f03el** [comment]
@smurfy FYI I'm working on an update to the Matka.fi backend because they are changing their API. Will try to have it finished before next week then.

**Comment by leppa** [comment]
@f03el, can you open a bug for this? I just created a 2.0.29 milestone and will assign your bug to it, so we can track the next release.

**Comment by f03el** [comment]
@leppa Nice, see #252.

**Comment by mikaelelf** [comment]
Is it far to go before a symbian update ?

/mikael
