### ISSUE TITLE
Since 3.3 (it appears) adding to calendar doesn't work.

### ISSUE THREAD

**Issue by poetaster** [smurfy/fahrplan#279]
This is coming from other users (I've never had calendar support on 3.4) via  openrepos:

"Smurfy, please fix the issue with adding journeys to the calendar. It appeared when I updated the Sailfish OS to version 3.3.0 (Rokua).
That is/was a awesome feature..."

**Comment by smurfy** [comment]
Implementation was quite tricky, also it was not in "official", store approved api, thats why only openrepos variant had it.

Needs looking into possible new api and store support.

**Comment by poetaster** [comment]
my workaround works for SFOS > 3.4. xdg open temp. cal files.
